### ISSUE TITLE
Clarify how to spawn when opening doors

### ISSUE THREAD

**Issue by skorokithakis** [danielhgasparin/zombicide-black-plague-spawner#20]
I just found this, and it's very useful, thanks! However, one question: What do we do when we open doors? How do we spawn zombies there?

**Comment by danielhgasparin** [comment]
Hi, and sorry for the loooong delay to respond.

To spawn inside buildings when you open a door, just set the number of spawn zones equal to the number of rooms in the building. The app will drawn spawn cards per room as if each rook are a spawn point.

**Comment by skorokithakis** [comment]
Thank you!
